// Code generated by go-bindata.
// sources:
// 0001_create_locations.down.sql
// 0001_create_locations.up.sql
// DO NOT EDIT!

package migrations

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __0001_create_locationsDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func _0001_create_locationsDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__0001_create_locationsDownSql,
		"0001_create_locations.down.sql",
	)
}

func _0001_create_locationsDownSql() (*asset, error) {
	bytes, err := _0001_create_locationsDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0001_create_locations.down.sql", size: 0, mode: os.FileMode(420), modTime: time.Unix(1534878501, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __0001_create_locationsUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\xcc\xb1\x6a\x85\x30\x14\xc6\xf1\xdd\xa7\x38\x64\x52\xe8\x58\xba\x74\x3a\x4d\x0f\x35\x34\x26\x72\x8c\x2d\x76\x29\x52\x83\x04\x34\x16\x3c\x1d\xfa\xf6\x17\xbd\xeb\xe5\x8e\x1f\xff\x1f\x9f\x66\xc2\x40\x10\xf0\xc5\x12\xa8\x65\xfb\x19\x25\x6d\x79\x57\x50\x16\x00\x2a\x4d\x0a\x3a\x62\x83\x16\x5a\x36\x0d\xf2\x00\xef\x34\x3c\x1c\x29\x66\x49\xf2\xaf\x40\xd7\xc8\xa8\x03\x31\x7c\x20\x0f\xc6\xbd\x95\x4f\x8f\xd5\x29\x96\x51\x92\xfc\x4d\x51\xc1\xab\xef\x8f\xfb\x96\x49\x9b\xce\x78\x77\xcd\x5b\x9e\xef\x75\x49\x6b\xdc\x65\x5c\x7f\x15\x04\xd3\x50\x17\xb0\x69\xe1\xd3\x84\xfa\x9c\xf0\xe5\x1d\x9d\x2e\xe5\x39\xee\xf2\x7d\x93\x3b\x1f\xc0\xf5\xd6\x16\xd5\xf3\x25\x00\x00\xff\xff\x19\x9c\x7f\x20\xe9\x00\x00\x00")

func _0001_create_locationsUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__0001_create_locationsUpSql,
		"0001_create_locations.up.sql",
	)
}

func _0001_create_locationsUpSql() (*asset, error) {
	bytes, err := _0001_create_locationsUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "0001_create_locations.up.sql", size: 233, mode: os.FileMode(420), modTime: time.Unix(1534878493, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"0001_create_locations.down.sql": _0001_create_locationsDownSql,
	"0001_create_locations.up.sql": _0001_create_locationsUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"0001_create_locations.down.sql": &bintree{_0001_create_locationsDownSql, map[string]*bintree{}},
	"0001_create_locations.up.sql": &bintree{_0001_create_locationsUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

